### ISSUE TITLE
require for proxy support again

### ISSUE THREAD

**Issue by lukemin** [klinker24/talon-for-twitter-android#123] opened 2019-06-10 08:00 UTC
hi Klinker24，
 you marked proxy support issue on 5 dec 2016，until now the proxy function has not been added. do you have any plan?

**Comment by klinker24** [comment] 2019-06-10 11:13
If the issue is still open, I still have plans to add it. Duplicate of #13

**Closed by klinker24** 2019-06-10 11:13 UTC

**Comment by lukemin** [comment] 2019-06-11 08:08
thanks， waiting for your nice work.
